### PR TITLE
MNIST_HandWrittenDigits_Dense_layer

### PR DESCRIPTION
**Pull request by shouryap1**
I have made this model using dense layer. There are 5 models in .ipynb file in which the 5th model has the highest accuracy. Also I have tried this model by giving custom input (Digits written by me and some other people and then given to the model to predict). I have also used various activation functions and loss function and came up with the best possible combination(which is model 5)

You can also predict a digit written by you through this model.

Much detail about project is given in PDF file present in the folder.

### CODE REVIEW

**Review by Anamaya1729 — CHANGES_REQUESTED** [review]
Please edit your notebook, clear the cells with errors. Add some comments and reasoning on the cells, refactor the code in the little professional way.

**Comment by shouryap1** [comment]
I have made required changes in the notebook

**Comment by Anamaya1729** [comment]
Thanks for the contribution. I just want to let you know that this project will shifted to the ML_advance/cnn_handwritten_recognition. It  will still be considered under hacktoberfest.

**Review by Anamaya1729 — APPROVED** [review]

**Comment by Anamaya1729** [comment]
Please change your pull_request to `ML_advance/cnn_handwrittern_digits_recognition/project_2` then your PR will be merged.

**Comment by shouryap1** [comment]
can you please guide me how to do that? or do I have to create a new PR?

**Comment by Anamaya1729** [comment]
move the files to ML_advance/project_2/ then create a commit.

**Comment by shouryap1** [comment]
I have done the required changes. Hope everything done is right.

**Review by Anamaya1729 — APPROVED** [review]

**Pull request merged**
