### PR TITLE
Heart Failure Prediction

### PR DESCRIPTION
**Pull request by shouryap1**
This is a heart failure prediction model. The dataset takes in account of many biological aspects. I performed different approaches to remove skewness from data so as to make model more accurate.

### CODE REVIEW

**Review by Anamaya1729 — CHANGES_REQUESTED** [review]
Please add a README.md file describing your project.

**Comment by Anamaya1729** [comment]
Your Project Notebook is really well done, just provide a README file to complete your contribution.

**Comment by shouryap1** [comment]
Hey @Anamaya1729, I have added the README file and thanks for appreciating the project.

**Review by Anamaya1729 — CHANGES_REQUESTED** [review]
Please format the README in md format, i.e. add headings using # Please check other readme files for the formatting guide.

**Comment by shouryap1** [comment]
I have updated the readme file and hope this is fine and has everything in it.

**Review by Anamaya1729 — APPROVED** [review]

**Comment by Anamaya1729** [comment]
Thanks for the contribution. Please star the repository to support the project,

**Pull request merged**
